# Generated by Django 4.2.3 on 2023-07-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFeedService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamtable',
            name='follower_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
