# Generated by Django 4.2.3 on 2023-08-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstaService', '0005_notification_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='parent_comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InstaService.comments'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='parent_post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InstaService.posts'),
        ),
    ]
