# Generated by Django 4.2.3 on 2023-08-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstaService', '0007_alter_comments_comment_alter_comments_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_picture',
        ),
    ]
