# Generated by Django 4.2.3 on 2023-08-18 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstaService', '0008_remove_comments_is_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeCountPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(default=0)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='InstaService.posts')),
            ],
        ),
        migrations.CreateModel(
            name='LikeCountComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(default=0)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='InstaService.comments')),
            ],
        ),
    ]
